SkyHigh.Web/Controllers/CitiesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SkyHigh.Models.Cities;
using SkyHigh.Models.Countries;
using SkyHigh.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SkyHigh.Web.Controllers
{
    public class CitiesController : Controller
    {
        private readonly ICitiesService citiesService;
        private readonly ICountriesService countriesService;

        public CitiesController(ICitiesService citiesService, ICountriesService countriesService)
        {
            this.citiesService = citiesService;
            this.countriesService = countriesService;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = await this.citiesService.GetAllCitiesAsync();

            return this.View(viewModel);
        }


        public async Task<IActionResult> Create()
        {
            var countries = await this.countriesService.GetAllCountriesAsync();

            var viewModel = new CityCreateInputModel()
            {
                Countries = countries.Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id
                })
                .ToList()
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CityCreateInputModel model)
        {
            bool isCityExisits = await this.citiesService.IsCityExistsAsync(model.Name, model.CountryId);

            if (isCityExisits)
            {
                this.ModelState.AddModelError("Name", "Provided city name already exists");
            }

            if (!this.ModelState.IsValid)
            {
                var countries = await this.countriesService.GetAllCountriesAsync();

                model.Countries = countries.Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id
                })
                .ToList();


                return this.View(model);
            }

            await this.citiesService.CreateCityAsync(model.Name, model.CountryId);

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Edit(string id)
        {
            var model = await this.citiesService.GetCityEditData(id);

            var countriesList = await this.countriesService.GetAllCountriesAsDropdownListAsync();

            model.Countries = countriesList;

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CityEditInputModel model)
        {

            bool isExisits = await this.citiesService.IsCityExistsAsync(model.NewName, model.CountryId);

            if (isExisits)
            {
                this.ModelState.AddModelError("NewName", "Provided city name already exists");
            }

            if (!this.ModelState.IsValid)
            {
                var countriesList = await this.countriesService.GetAllCountriesAsDropdownListAsync();
                model.Countries = countriesList;
                return this.View(model);
            }

            await this.citiesService.UpdateCityAsync(model.Id, model.NewName, model.CountryId);

            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return RedirectToAction("Index"); //TODO: Redirect to error
            }

            bool sucess = await this.citiesService.DeleteByIdAsync(id);

            if (sucess == false)
            {
                return RedirectToAction("Index"); //TODO: Redirect to error
            }

            return RedirectToAction("Index");
        }
    }
}

SkyHigh.Web/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SkyHigh.Models.Countries;
using SkyHigh.Services;

namespace SkyHigh.Web.Controllers
{
    public class CountriesController : Controller
    {
        private readonly ICountriesService countriesService;

        public CountriesController(ICountriesService countriesService)
        {
            this.countriesService = countriesService;
        }


        public async Task<ActionResult> Index()
        {
            var viewModel = await this.countriesService.GetAllCountriesWithCitiesAsync();

            return this.View(viewModel);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CountryCreateInputModel model)
        {
            bool isExisits = await this.countriesService.IsCountryExistsAsync(model.Name);

            if (isExisits)
            {
                this.ModelState.AddModelError("Name", "Provided country name already exists");
            }

            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.countriesService.CreateCountryAsync(model.Name);

            return RedirectToAction(nameof(Index));

        }

        public async Task<ActionResult> Edit(string id)
        {
            var model = await this.countriesService.GetCountryEditData(id);

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CountryEditInputModel model)
        {
            bool isExisits = await this.countriesService.IsCountryExistsAsync(model.NewName);

            if (isExisits)
            {
                this.ModelState.AddModelError("NewName", "Provided country name already exists");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.countriesService.UpdateCountryAsync(model.Id, model.NewName);

            return RedirectToAction(nameof(Index));
        }

        // GET: Countries/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Countries/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SkyHigh.Web/Views/Countries/Create.cshtml
@model SkyHigh.Models.Countries.CountryCreateInputModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CountryInputModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @*<div asp-validation-summary="All" class="text-danger"></div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SkyHigh.Web/Views/Countries/Edit.cshtml
@model SkyHigh.Models.Countries.CountryEditInputModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit a country</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-group">
                <label asp-for="CurrentName" class="control-label"></label>
                <input asp-for="CurrentName" class="form-control" disabled />
                <input asp-for="CurrentName" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="NewName" class="control-label"></label>
                <input asp-for="NewName" class="form-control" />
                <span asp-validation-for="NewName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SkyHigh.Web/Views/Countries/Index.cshtml
@model IEnumerable<SkyHigh.Models.Countries.CountryIndexViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Countries</h2>
<hr />

<div>
    <a class="btn btn-primary" asp-action="Create">Add new Country</a>
</div>

<h3 class="text-center">Countries List</h3>

<table class="table table-hover" style="width: 100%">
    <thead>
        <tr>
            <th>Country Name</th>
            <th>Cities</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var country in Model)
        {
            <tr>
                <td>@country.Name</td>
                <td>@string.Join(", ", country.Cities)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@country.Id" class="btn btn-outline-primary">Edit</a>
                    @if (country.Cities.Count() == 0)
                    {
                        <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal" data-cityid="@country.Id" data-cityname="@country.Name">Delete</button>
                    }
                    else
                    {
                        <button type="button" class="btn btn-outline-primary" disabled>Delete</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-controller="Cities" asp-action="Index" class="btn btn-secondary">Go to cities</a>
</div>