SkyHigh.Web/Controllers/AirportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SkyHigh.Models.Airports;
using SkyHigh.Services;

namespace SkyHigh.Web.Controllers
{
    public class AirportsController : Controller
    {

        private readonly IAirportsService airportsService;
        private readonly ICitiesService citiesService;

        public AirportsController(IAirportsService airportsService, ICitiesService citiesService)
        {
            this.airportsService = airportsService;
            this.citiesService = citiesService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await this.airportsService.GetAllAirportsAsync();
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            var model = new AirportCreateInputModel();
            model.Cities = await this.citiesService.GetAllCitiesAsDropdownListAsync();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AirportCreateInputModel model)
        {
            bool isAirportExists = await this.airportsService.IsAirportExistsAsync(model.IcaoCode);

            if (isAirportExists)
            {
                this.ModelState.AddModelError("IcaoCode", "Provided ICAO Code already exists");
            }

            if (!this.ModelState.IsValid)
            {
                model.Cities = await this.citiesService.GetAllCitiesAsDropdownListAsync();
                return this.View(model);
            }

            await this.airportsService.CreateAirportAsync(model);

            return RedirectToAction("Index");
        }

    }
}

SkyHigh.Web/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SkyHigh.Models.Countries;
using SkyHigh.Services;

namespace SkyHigh.Web.Controllers
{
    public class CountriesController : Controller
    {
        private readonly ICountriesService countriesService;

        public CountriesController(ICountriesService countriesService)
        {
            this.countriesService = countriesService;
        }


        public async Task<ActionResult> Index()
        {
            var viewModel = await this.countriesService.GetAllCountriesWithCitiesAsync();

            return this.View(viewModel);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CountryCreateInputModel model)
        {
            bool isExisits = await this.countriesService.IsCountryExistsAsync(model.Name);

            if (isExisits)
            {
                this.ModelState.AddModelError("Name", "Provided country name already exists");
            }

            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.countriesService.CreateCountryAsync(model.Name);

            return RedirectToAction(nameof(Index));

        }

        public async Task<ActionResult> Edit(string id)
        {
            var model = await this.countriesService.GetCountryEditData(id);

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CountryEditInputModel model)
        {
            bool isExisits = await this.countriesService.IsCountryExistsAsync(model.NewName);

            if (isExisits)
            {
                this.ModelState.AddModelError("NewName", "Provided country name already exists");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.countriesService.UpdateCountryAsync(model.Id, model.NewName);

            return RedirectToAction(nameof(Index));
        }

        // GET: Countries/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Countries/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SkyHigh.Web/Views/Airports/Create.cshtml
@model SkyHigh.Models.Airports.AirportCreateInputModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AirportCreateInputModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IcaoCode" class="control-label"></label>
                <input asp-for="IcaoCode" class="form-control" />
                <span asp-validation-for="IcaoCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cities" class="control-label"></label>
                <select class="custom-select" asp-for="CityId" asp-items="@Model.Cities">
                    <option value="" selected="">Please select a city...</option>
                </select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SkyHigh.Web/Views/Airports/Index.cshtml
@model IEnumerable<SkyHigh.Models.Airports.AirportIndexViewModel>

@{
    ViewData["Title"] = "Index";
}
<h2>Airports</h2>
<hr />

<div>
    <a class="btn btn-primary" asp-action="Create">Add new Airport</a>
</div>

<h3 class="text-center">Airport List</h3>
<table class="table table-hover" style="width: 100%">
    <thead>
        <tr>
            <th>ICAO Code</th>
            <th>Airport Name</th>
            <th>City</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var airport in Model)
        {
            <tr>
                <td>@airport.IcaoCode</td>
                <td>@airport.Name</td>
                <td>@airport.CityName</td>
                <td class="justify-content-center">
                    <a asp-action="Edit" asp-route-id="@airport.Id" class="btn btn-outline-primary">Edit</a>
                    @if (true)
                    {
                        <btton type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal" data-cityid="@airport.Id" data-cityname="@airport.Name">Delete</btton>
                    }
                    else
                    {
                        <button type="button" class="btn btn-outline-primary" disabled>Delete</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-controller="Countries" asp-action="Index" class="btn btn-secondary">Go to countries</a>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete a City</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <label>Are you sure?</label>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="/Cities/Delete" method="Post">
                    <input type="hidden" name="id" value="placeholder">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        $('#exampleModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var cityId = button.data('cityid')
            var cityName = button.data('cityname')
            var modal = $(this)
            modal.find('.modal-body label').text('Are you sure you want to delete "' + cityName + '" city?')
            modal.find('.modal-footer input').val(cityId)
        })
    </script>
}